import { Marked } from 'marked'
import DOMPurify, { type Config as DOMPurifyConfig } from 'dompurify'

// The U+2028 character (LINE SEPARATOR) is sometimes used as a line break, but it is treated as a space in some web environments,
// causing unexpected rendering issues. To avoid this, it's recommended to replace it with a standard line break character such as `\n`.
const LINE_SEPARATOR = /\u2028/g

// LINE_BREAK_VISUAL is used for formatting when the message is displayed as a single line in a preview.
// It replaces line breaks with a visual symbol (↵) to indicate where new lines exist in the original text.
const LINE_BREAK_VISUAL = '↵ '

// DOMPurify configuration applied to the HTML output of marked.parse().
// Only tags and attributes needed for safe markdown display are allowed.
const MARKDOWN_DOMPURIFY_CONFIG: DOMPurifyConfig = {
  ALLOWED_TAGS: [
    'p',
    'br',
    'b',
    'i',
    'em',
    'strong',
    'a',
    'code',
    'pre',
    'ul',
    'ol',
    'li',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'blockquote'
  ],
  ALLOWED_ATTR: ['href', 'target', 'rel'],
  // target and rel carry non-URI values (_blank, noopener noreferrer).
  // Adding them to ADD_URI_SAFE_ATTR exempts their values from URI validation,
  // which would otherwise strip them as "not a valid URI".
  ADD_URI_SAFE_ATTR: ['target', 'rel'],
  // Extend the default URI allowlist to cover the same protocols accepted by renderer.link.
  // Without this, DOMPurify silently strips href values for schemes like eth:, bitcoin:,
  // magnet:, tg:, tor:, onion:, sftp: that are not in the DOMPurify built-in list.
  ALLOWED_URI_REGEXP:
    /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|sms|cid|xmpp|matrix|eth|bch|bitcoin|magnet|tor|onion|tg|s?ftp):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i
}

const marked = new Marked()

marked.setOptions({
  // marked sanitize is deprecated, using DOMPurify
  // sanitize: true,
  gfm: true,
  breaks: true
})

const renderer = new marked.Renderer()

renderer.image = function () {
  return ''
}

renderer.link = function ({ href, text }) {
  const linkPattern = /^(eth|bch|bitcoin|https?|s?ftp|magnet|tor|onion|tg):(.*)$/i
  const emailPattern = /^(mailto):[^@]+@[^@]+\.[^@]+$/i

  // Escape double quotes so the href cannot break out of the HTML attribute boundary.
  // The full HTML output is also sanitized by DOMPurify after marked.parse().
  if (linkPattern.test(href)) {
    const safeHref = href.replace(/"/g, '%22')
    return `<a href="${safeHref}" target="_blank" rel="noopener noreferrer">${safeHref}</a>`
  } else if (emailPattern.test(href)) {
    const safeHref = href.replace(/"/g, '%22')
    return `<a href="${safeHref}">${text}</a>`
  }

  return text
}

renderer.heading = function ({ text, depth }) {
  return `<h${depth}>${text}</h${depth}>`
}

marked.use({ renderer })

/**
 * Sanitizes text to show HTML
 * @param {string} text text to sanitize
 * @returns {string} sanitized HTML
 */
export function sanitizeHTML(text = '') {
  return DOMPurify.sanitize(text)
}

/**
 * Renders markdown-formatted input to HTML, and sanitizes it
 * @param {string} text text to render
 * @returns {string} resulting sanitized HTML
 */
export function renderMarkdown(text = '') {
  // Parse markdown first, then sanitize the HTML output.
  // Sanitizing the raw markdown text first (wrong order) does not protect against
  // XSS payloads that are generated by the markdown parser itself.
  const rawHtml = marked.parse(text.replace(LINE_SEPARATOR, '\n'), { async: false }) as string
  return DOMPurify.sanitize(rawHtml, MARKDOWN_DOMPURIFY_CONFIG)
}

/**
 * Gets the first line of a message, sanitizes it, and returns back
 * Used in ChatPreview and Notifications
 * @param {string} text text to process
 * @returns {string} resulting clear text of the first line
 */
export function formatMessageBasic(text = '') {
  const node = document.createElement('div')

  const textWithSymbol = text.replace(/\n/g, LINE_BREAK_VISUAL)
  const rawHtml = marked.parse(textWithSymbol, { async: false })
  node.innerHTML = DOMPurify.sanitize(rawHtml, MARKDOWN_DOMPURIFY_CONFIG)

  let textWithoutHtml = node.textContent || node.innerText || ''

  textWithoutHtml = textWithoutHtml
    .replace(LINE_SEPARATOR, LINE_BREAK_VISUAL)
    .split(LINE_BREAK_VISUAL)
    // strip all markdown heading signs (#) but only if they are at the beginning of the line
    .map((line) => line.replace(/^[#]+ /, ''))
    .join(LINE_BREAK_VISUAL)

  return textWithoutHtml
}

/**
 * Formats a message for display in a chat preview
 * @param {string} text text to process
 * @returns {string} resulting clear text of the first line
 */
export function formatChatPreviewMessage(text = '') {
  return formatMessageBasic(text).replace(/↵/g, '<span class="arrow-return">↵</span>')
}
