language: node_js
node_js:
  - "node"
os:
  - linux
cache:
  directories:
    - node_modules
install:
  - npm install
deploy:
  provider: surge
  project: ./dist/
  domain: $TRAVIS_BRANCH-adamant-im.surge.sh  
  skip_cleanup: true
  on:
    all_branches: true
script: npm run build
