language: node_js
node_js:
  - "lts/*"
os:
  - linux
cache:
  directories:
    - node_modules
install:
  - yarn install
before_deploy:
  - source ./deploy.sh
deploy:
  provider: surge
  project: ./dist/
  domain: $SUBDOMAIN-adamant-im.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
script: yarn run build
