import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const currentDir = path.dirname(fileURLToPath(import.meta.url))
const optionsPath = path.resolve(currentDir, '../Options.vue')
const genericTokensPath = path.resolve(currentDir, '../../assets/styles/generic/_tokens.scss')
const textContentPath = path.resolve(
  currentDir,
  '../../assets/styles/components/_text-content.scss'
)

describe('Options UI style contract', () => {
  it('uses shared interactive opacity tokens', () => {
    const content = readFileSync(genericTokensPath, 'utf8')

    expect(content).toContain('--a-opacity-interactive-hover')
    expect(content).toContain('--a-opacity-interactive-pressed')
  })

  it('uses tokenized settings spacing and typography variables', () => {
    const content = readFileSync(optionsPath, 'utf8')
    const textContent = readFileSync(textContentPath, 'utf8')

    expect(content).toContain('--a-settings-gutter')
    expect(content).toContain('--a-settings-title-padding-top')
    expect(content).toContain('--a-settings-title-margin-top-section')
    expect(content).toContain('--a-settings-title-margin-bottom-first')
    expect(content).toContain('--a-settings-title-margin-bottom-section')
    expect(content).toContain('--a-settings-actions-row-min-height')
    expect(content).toContain('--a-settings-actions-row-padding-block')
    expect(content).toContain('--a-settings-logout-margin-top')
    expect(content).toContain('--a-settings-option-offset')
    expect(content).toContain('--a-settings-version-info-hover-opacity')
    expect(content).toContain('--a-settings-version-info-active-opacity')
    expect(content).toContain('var(--a-list-row-min-height)')
    expect(content).toContain('var(--a-list-row-padding-block)')
    expect(content).toContain('var(--a-opacity-interactive-hover)')
    expect(content).toContain('var(--a-opacity-interactive-pressed)')
    expect(content).toContain('var(--a-color-text-muted-light)')
    expect(content).toContain('var(--a-color-surface-soft-light)')
    expect(content).toContain('var(--a-color-border-soft-light)')
    expect(content).toContain('var(--a-color-text-muted-dark)')
    expect(content).toContain("const SETTINGS_STATE_RESET_KEY = 'resetSettingsView'")
    expect(content).toContain("const SETTINGS_STATE_FORCE_RESET_KEY = 'forceResetSettingsView'")
    expect(content).toContain("const SETTINGS_PATH_PREFIX = '/options'")
    expect(content).toContain('const isLoggingOut = ref(false)')
    expect(content).toContain(
      'const isSettingsPath = (path: string) => path.startsWith(SETTINGS_PATH_PREFIX)'
    )
    expect(content).toContain("store.commit('options/setSettingsLastRoute', path)")
    expect(content).toContain("store.getters['options/settingsScrollPosition'](path)")
    expect(content).toContain('let settingsRestoreObserver: ResizeObserver | null = null')
    expect(content).toContain('const stopSettingsRestore = () => {')
    expect(content).toContain('const finalizeRestore = (restoredTop: number) => {')
    expect(content).toContain('new ResizeObserver(() => {')
    expect(content).toContain('const navigateToSettingsChild = (path: string) => {')
    expect(content).toContain('isLoggingOut.value = true')
    expect(content).toContain('resetSettingsView: savedTop <= 0')
    expect(content).toContain('window.history.state?.[SETTINGS_STATE_FORCE_RESET_KEY]')
    expect(content).toContain('if (isRestoringSettingsScroll.value || isLoggingOut.value)')
    expect(content).toContain('if (!isRestoringSettingsScroll.value && !isLoggingOut.value)')
    expect(content).toContain('@click="navigateToSettingsChild(\'/options/nodes\')"')
    expect(content).toContain('@click="navigateToSettingsChild(\'/options/wallets\')"')
    expect(content).toContain('window.history.state?.[SETTINGS_STATE_RESET_KEY]')
    expect(content).toContain(':deep(.a-switcher-button)')
    expect(content).toContain('&__logout')
    expect(content).toContain('&__control-col')
    expect(content).toContain('&__option-offset')
    expect(content).toContain('textContent.a-content-explanatory-copy()')
    expect(content).toContain('&__title--first')
    expect(content).toContain('&__title--section')
    expect(content).toContain('<button')
    expect(content).toContain('type="button"')
    expect(content).toContain("theme.change(isDarkTheme ? 'dark' : 'light')")
    expect(content).toContain('var(--a-space-6)')
    expect(content).not.toContain("theme.global.name.value = isDarkTheme ? 'dark' : 'light'")
    expect(content).not.toContain('class="mt-4 mb-4"')
    expect(content).not.toContain('class="mt-6 mb-6"')
    expect(content).not.toContain('class="text-right"')
    expect(content).not.toContain('class="mt-6"')
    expect(content).not.toContain('ml-auto')
    expect(content).not.toContain('cursor: pointer;')
    expect(content).not.toContain("color: map.get(colors.$adm-colors, 'muted');")
    expect(content).not.toMatch(/(^|\n)\s*padding-top:\s*15px;/)
    expect(content).toContain('min-height: var(--a-settings-actions-row-min-height);')
    expect(content).toContain('padding-top: var(--a-settings-actions-row-padding-block);')
    expect(content).toContain('padding-bottom: var(--a-settings-actions-row-padding-block);')
    expect(content).not.toContain('--a-settings-action-font-size')
    expect(content).not.toContain('--a-settings-action-font-weight')
    expect(content).not.toContain('--a-settings-action-margin-block')
    expect(content).not.toContain('&__action')
    expect(content).not.toContain('--a-settings-gutter: var(--a-space-4);')
    expect(content).not.toContain('opacity: 0.8;')
    expect(content).not.toContain('opacity: 0.6;')
    expect(textContent).toContain('@mixin a-content-explanatory-copy()')
  })
})
