import { readFileSync } from 'node:fs'
import path from 'node:path'
import { normalizePath, type Plugin } from 'vite'

export type NetworkBuildTarget = 'pwa' | 'electron' | 'android' | 'vitest'
export type NetworkConfigVariant = 'development' | 'production' | 'testnet' | 'tor'
type NetworkName = 'mainnet' | 'testnet' | 'tor'

type EndpointEntry = { url?: unknown; alt_ip?: unknown }
type EndpointList = { list?: EndpointEntry[] }
type CoinNetworkConfig = {
  explorer?: unknown
  explorerTx?: unknown
  explorerAddress?: unknown
  nodes?: EndpointList
  services?: Record<string, EndpointList>
}

export type NetworkConfig = Record<string, CoinNetworkConfig>
export type NetworkConfigReferences = { mainnet: NetworkConfig; testnet: NetworkConfig }

/** Import specifier that resolves to the one generated network configuration of the build */
export const NETWORK_CONFIG_MODULE_ID = 'virtual:adamant-network-config'

/** Generated by `npm run wallets:data:generate` into `src/config/<variant>.json` */
export const NETWORK_CONFIG_VARIANTS: readonly NetworkConfigVariant[] = [
  'development',
  'production',
  'testnet',
  'tor'
]

/** Vite modes supported by each build target, mapped to the network configuration they bundle */
export const SUPPORTED_NETWORK_MODES: Readonly<
  Record<NetworkBuildTarget, Readonly<Record<string, NetworkConfigVariant>>>
> = {
  pwa: { development: 'development', production: 'production', testnet: 'testnet', tor: 'tor' },
  electron: { development: 'development', production: 'production' },
  android: { development: 'development', production: 'production' },
  vitest: { test: 'development' }
}

const NETWORK_BY_VARIANT: Readonly<Record<NetworkConfigVariant, NetworkName>> = {
  development: 'mainnet',
  production: 'mainnet',
  testnet: 'testnet',
  tor: 'tor'
}

const EXPLORER_FIELDS = ['explorer', 'explorerTx', 'explorerAddress'] as const

/**
 * Selects the generated network configuration for a build target and Vite mode.
 * Unsupported combinations fail instead of silently composing incompatible networks.
 */
export function resolveNetworkConfigVariant(
  target: NetworkBuildTarget,
  mode: string
): NetworkConfigVariant {
  const modes = SUPPORTED_NETWORK_MODES[target]

  if (Object.hasOwn(modes, mode)) {
    return modes[mode]
  }

  const supportedModes = Object.keys(modes)
    .map((supportedMode) => `"${supportedMode}"`)
    .join(', ')
  const reason =
    mode === 'tor-testnet'
      ? 'The Tor network configuration describes mainnet endpoints and cannot be combined with testnet.'
      : Object.hasOwn(SUPPORTED_NETWORK_MODES.pwa, mode)
        ? 'Testnet and Tor network configurations are built only for the PWA target.'
        : 'The mode has no generated network configuration.'

  throw new Error(
    `Unsupported Vite mode "${mode}" for the ${target} build target. ${reason} ` +
      `Supported modes: ${supportedModes}`
  )
}

/**
 * Lists every node and service endpoint, including alternative IP endpoints.
 */
export function collectNetworkEndpoints(config: NetworkConfig): { path: string; url: unknown }[] {
  return Object.entries(config).flatMap(([coin, coinConfig]) => [
    ...collectListEndpoints(`${coin}.nodes`, coinConfig.nodes),
    ...Object.entries(coinConfig.services ?? {}).flatMap(([service, serviceConfig]) =>
      collectListEndpoints(`${coin}.services.${service}`, serviceConfig)
    )
  ])
}

/**
 * Checks the runtime network contract of one generated configuration:
 *
 * - Tor node and service endpoints use onion hosts, while explorer links may stay clearnet
 * - Mainnet and testnet node and service endpoints do not use onion hosts
 * - Mainnet and testnet do not share ADM node, IPFS node, or ADM explorer origins
 */
export function findNetworkConfigViolations(
  variant: NetworkConfigVariant,
  config: NetworkConfig,
  references: NetworkConfigReferences
): string[] {
  const network = NETWORK_BY_VARIANT[variant]
  const violations: string[] = []

  for (const [coin, coinConfig] of Object.entries(config)) {
    for (const field of EXPLORER_FIELDS) {
      const value = coinConfig[field]

      if (value !== undefined && !parseHttpUrl(value)) {
        violations.push(`${coin}.${field}: invalid HTTP(S) URL ${JSON.stringify(value)}`)
      }
    }
  }

  for (const { path: endpointPath, url } of collectNetworkEndpoints(config)) {
    const endpoint = parseHttpUrl(url)

    if (!endpoint) {
      violations.push(`${endpointPath}: invalid HTTP(S) endpoint ${JSON.stringify(url)}`)
    } else if (network === 'tor' && !isOnionHost(endpoint)) {
      violations.push(`${endpointPath}: Tor endpoints must use onion hosts, found ${url}`)
    } else if (network !== 'tor' && isOnionHost(endpoint)) {
      violations.push(
        `${endpointPath}: ${network} endpoints must not use onion hosts, found ${url}`
      )
    }
  }

  if (network !== 'tor') {
    const otherNetwork = network === 'mainnet' ? 'testnet' : 'mainnet'
    const forbiddenOrigins = new Set(
      collectAdmNetworkOrigins(references[otherNetwork]).map(({ origin }) => origin)
    )

    for (const { path: fieldPath, origin } of collectAdmNetworkOrigins(config)) {
      if (forbiddenOrigins.has(origin)) {
        violations.push(
          `${fieldPath}: ${network} configuration uses the ${otherNetwork} origin ${origin}`
        )
      }
    }
  }

  return violations
}

/**
 * Checks that a bundle contains exactly the expected generated network configuration module.
 */
export function findBundledNetworkConfigViolations(
  expectedVariant: NetworkConfigVariant,
  moduleIds: Iterable<string>,
  configsDir: string
): string[] {
  const variantsByPath = new Map(
    NETWORK_CONFIG_VARIANTS.map((variant) => [getNetworkConfigPath(configsDir, variant), variant])
  )
  const bundledVariants = new Set<NetworkConfigVariant>()

  for (const moduleId of moduleIds) {
    const variant = variantsByPath.get(normalizePath(moduleId.split('?')[0]))

    if (variant) {
      bundledVariants.add(variant)
    }
  }

  const violations = [...bundledVariants]
    .filter((variant) => variant !== expectedVariant)
    .map((variant) => `the bundle includes the ${variant} network configuration`)

  if (!bundledVariants.has(expectedVariant)) {
    violations.unshift(`the bundle does not include the ${expectedVariant} network configuration`)
  }

  return violations
}

/**
 * Resolves `virtual:adamant-network-config` to the generated configuration of the current mode,
 * rejects unsupported modes, and verifies the emitted bundle against the network contract.
 */
export function networkConfigPlugin(target: NetworkBuildTarget): Plugin {
  let variant: NetworkConfigVariant
  let configsDir: string
  let isBuild = false

  return {
    name: 'adamant-network-config',
    enforce: 'pre',

    configResolved(config) {
      variant = resolveNetworkConfigVariant(target, config.mode)
      configsDir = path.resolve(config.root, 'src', 'config')
      isBuild = config.command === 'build'
    },

    resolveId(id) {
      return id === NETWORK_CONFIG_MODULE_ID ? getNetworkConfigPath(configsDir, variant) : null
    },

    generateBundle(_options, bundle) {
      if (!isBuild) return

      const moduleIds = Object.values(bundle).flatMap((output) =>
        output.type === 'chunk' ? output.moduleIds : []
      )
      const violations = [
        ...findBundledNetworkConfigViolations(variant, moduleIds, configsDir),
        ...findNetworkConfigViolations(variant, readNetworkConfig(configsDir, variant), {
          mainnet: readNetworkConfig(configsDir, 'production'),
          testnet: readNetworkConfig(configsDir, 'testnet')
        })
      ]

      if (violations.length > 0) {
        this.error(
          `Network configuration build gate rejected the ${variant} bundle:\n${violations.join('\n')}`
        )
      }
    }
  }
}

function getNetworkConfigPath(configsDir: string, variant: NetworkConfigVariant): string {
  return normalizePath(path.join(configsDir, `${variant}.json`))
}

function readNetworkConfig(configsDir: string, variant: NetworkConfigVariant): NetworkConfig {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- variant names come from a fixed allowlist
  return JSON.parse(readFileSync(getNetworkConfigPath(configsDir, variant), 'utf8'))
}

function collectListEndpoints(listPath: string, endpointList: EndpointList | undefined) {
  return (endpointList?.list ?? []).flatMap((entry, index) => [
    { path: `${listPath}.list[${index}].url`, url: entry.url },
    ...(entry.alt_ip === undefined
      ? []
      : [{ path: `${listPath}.list[${index}].alt_ip`, url: entry.alt_ip }])
  ])
}

function collectAdmNetworkOrigins(config: NetworkConfig): { path: string; origin: string }[] {
  const adm = config.adm ?? {}
  const fields = [
    ...collectListEndpoints('adm.nodes', adm.nodes),
    ...collectListEndpoints('adm.services.ipfsNode', adm.services?.ipfsNode),
    ...EXPLORER_FIELDS.map((field) => ({ path: `adm.${field}`, url: adm[field] }))
  ]

  return fields.flatMap(({ path: fieldPath, url }) => {
    const parsedUrl = parseHttpUrl(url)

    return parsedUrl ? [{ path: fieldPath, origin: parsedUrl.origin }] : []
  })
}

function parseHttpUrl(value: unknown): URL | null {
  if (typeof value !== 'string') return null

  try {
    const url = new URL(value)

    return url.protocol === 'http:' || url.protocol === 'https:' ? url : null
  } catch {
    return null
  }
}

function isOnionHost(url: URL): boolean {
  return url.hostname.endsWith('.onion')
}
