import { readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { normalizePath, type Plugin } from 'vite'

export type NetworkBuildTarget = 'pwa' | 'electron' | 'android' | 'vitest'
export type NetworkConfigVariant = 'mainnet' | 'testnet' | 'tor'

type EndpointEntry = { url?: unknown; alt_ip?: unknown }
type EndpointList = { list?: EndpointEntry[]; healthCheck?: unknown }
type CoinNetworkConfig = {
  explorer?: unknown
  explorerTx?: unknown
  explorerAddress?: unknown
  nodes?: EndpointList
  services?: Record<string, EndpointList>
}

export type NetworkConfig = Record<string, CoinNetworkConfig>
export type NetworkConfigReferences = { mainnet: NetworkConfig; testnet: NetworkConfig }

/** Import specifier that resolves to the one generated network configuration of the build */
export const NETWORK_CONFIG_MODULE_ID = 'virtual:adamant-network-config'

/** Generated by `npm run wallets:data:generate` into `src/config/<variant>.json` */
export const NETWORK_CONFIG_VARIANTS: readonly NetworkConfigVariant[] = [
  'mainnet',
  'testnet',
  'tor'
]

/**
 * Vite modes supported by each build target, mapped to the network configuration they bundle.
 * The `development` and `production` modes change build behavior, not network endpoints, so both
 * bundle `mainnet`.
 */
export const SUPPORTED_NETWORK_MODES: Readonly<
  Record<NetworkBuildTarget, Readonly<Record<string, NetworkConfigVariant>>>
> = {
  pwa: { development: 'mainnet', production: 'mainnet', testnet: 'testnet', tor: 'tor' },
  electron: { development: 'mainnet', production: 'mainnet' },
  android: { development: 'mainnet', production: 'mainnet' },
  vitest: { test: 'mainnet' }
}

const EXPLORER_FIELDS = ['explorer', 'explorerTx', 'explorerAddress'] as const

const NETWORK_CONFIG_URL_MARKER = '__ADAMANT_NETWORK_CONFIG_URL__:'
const NETWORK_CONFIG_URL_REGISTRY = '__ADAMANT_NETWORK_CONFIG_URLS__'
const STRING_DELIMITER_PATTERN = `["'\\x60]`
const MARKED_NETWORK_CONFIG_URL_PATTERN = new RegExp(
  `${NETWORK_CONFIG_URL_REGISTRY}\\[(?:${STRING_DELIMITER_PATTERN})${NETWORK_CONFIG_URL_MARKER}([^"'\\\\\x60]+)(?:${STRING_DELIMITER_PATTERN})\\]\\s*=\\s*(?:${STRING_DELIMITER_PATTERN})(https?:\\/\\/[^"'\\\\\x60]+)(?:${STRING_DELIMITER_PATTERN})`,
  'g'
)
const MARKED_NETWORK_CONFIG_URL_EXPRESSION_PATTERN = new RegExp(
  `\\(globalThis\\.${NETWORK_CONFIG_URL_REGISTRY}\\s*\\?\\?=\\s*\\{\\},\\s*globalThis\\.${NETWORK_CONFIG_URL_REGISTRY}\\[(?:${STRING_DELIMITER_PATTERN})${NETWORK_CONFIG_URL_MARKER}([^"'\\\\\x60]+)(?:${STRING_DELIMITER_PATTERN})\\]\\s*=\\s*((?:${STRING_DELIMITER_PATTERN})https?:\\/\\/[^"'\\\\\x60]+(?:${STRING_DELIMITER_PATTERN}))\\)`,
  'g'
)

const REQUIRED_NETWORK_RUNTIME_CONTRACT: Readonly<
  Record<string, { requiredServices?: readonly string[] }>
> = {
  adm: { requiredServices: ['infoService', 'ipfsNode'] },
  btc: { requiredServices: ['btcIndexer'] },
  dash: {},
  doge: { requiredServices: ['dogeIndexer'] },
  eth: { requiredServices: ['ethIndexer'] }
}

/**
 * Selects the generated network configuration for a build target and Vite mode.
 * Unsupported combinations fail instead of silently composing incompatible networks.
 */
export function resolveNetworkConfigVariant(
  target: NetworkBuildTarget,
  mode: string
): NetworkConfigVariant {
  const modes = SUPPORTED_NETWORK_MODES[target]

  if (Object.hasOwn(modes, mode)) {
    return modes[mode]
  }

  const supportedModes = Object.keys(modes)
    .map((supportedMode) => `"${supportedMode}"`)
    .join(', ')
  const reason =
    mode === 'tor-testnet'
      ? 'The Tor network configuration describes mainnet endpoints and cannot be combined with testnet.'
      : Object.hasOwn(SUPPORTED_NETWORK_MODES.pwa, mode)
        ? 'Testnet and Tor network configurations are built only for the PWA target.'
        : 'The mode has no generated network configuration.'

  throw new Error(
    `Unsupported Vite mode "${mode}" for the ${target} build target. ${reason} ` +
      `Supported modes: ${supportedModes}`
  )
}

/**
 * Lists every node and service endpoint, including alternative IP endpoints.
 */
export function collectNetworkEndpoints(config: NetworkConfig): { path: string; url: unknown }[] {
  return Object.entries(config).flatMap(([coin, coinConfig]) => [
    ...collectListEndpoints(`${coin}.nodes`, coinConfig.nodes),
    ...Object.entries(coinConfig.services ?? {}).flatMap(([service, serviceConfig]) =>
      collectListEndpoints(`${coin}.services.${service}`, serviceConfig)
    )
  ])
}

/**
 * Checks that the configuration has the shape the runtime node clients expect. An absent or
 * malformed endpoint list would otherwise pass the endpoint rules as an empty list and ship a build
 * without usable nodes or services.
 *
 * The mainnet configuration defines the required coins and services, so a testnet or Tor variant
 * cannot silently drop one of them.
 */
export function findNetworkConfigSchemaViolations(config: NetworkConfig): string[] {
  if (!isPlainObject(config)) {
    return ['the network configuration is not an object']
  }

  const coins = Object.keys(config)
  const violations = coins.length === 0 ? ['the network configuration has no coins'] : []

  for (const [coin, coinConfig] of Object.entries(config)) {
    if (!isPlainObject(coinConfig)) {
      violations.push(`${coin}: expected an object`)
      continue
    }

    if (coinConfig.nodes !== undefined) {
      violations.push(...findEndpointListViolations(`${coin}.nodes`, coinConfig.nodes))
    }

    if (coinConfig.services !== undefined && !isPlainObject(coinConfig.services)) {
      violations.push(`${coin}.services: expected an object`)
      continue
    }

    const services = getServices(coinConfig)

    for (const [service, serviceConfig] of Object.entries(services)) {
      violations.push(...findEndpointListViolations(`${coin}.services.${service}`, serviceConfig))
    }
  }

  for (const [coin, contract] of Object.entries(REQUIRED_NETWORK_RUNTIME_CONTRACT)) {
    const coinConfig = config[coin]

    if (!isPlainObject(coinConfig)) {
      violations.push(`${coin}: missing coin configuration`)
      continue
    }

    for (const field of EXPLORER_FIELDS) {
      if (typeof coinConfig[field] !== 'string') {
        violations.push(`${coin}.${field}: expected a string`)
      }
    }

    violations.push(...findEndpointListViolations(`${coin}.nodes`, coinConfig.nodes))

    if (isPlainObject(coinConfig.nodes) && !isPlainObject(coinConfig.nodes.healthCheck)) {
      violations.push(`${coin}.nodes.healthCheck: expected an object`)
    }

    if (coinConfig.services !== undefined && !isPlainObject(coinConfig.services)) {
      violations.push(`${coin}.services: expected an object`)
      continue
    }

    const services = getServices(coinConfig)

    for (const service of contract.requiredServices ?? []) {
      const serviceConfig = services[service]

      violations.push(...findEndpointListViolations(`${coin}.services.${service}`, serviceConfig))

      if (isPlainObject(serviceConfig) && !isPlainObject(serviceConfig.healthCheck)) {
        violations.push(`${coin}.services.${service}.healthCheck: expected an object`)
      }
    }
  }

  return [...new Set(violations)]
}

/**
 * Checks the runtime network contract of one generated configuration:
 *
 * - The configuration has the coins, node lists, and service lists the runtime expects
 * - Tor node and service endpoints use onion hosts, and so do the ADM explorer links
 * - Tor keeps the clearnet BTC, DASH, DOGE, and ETH explorer links of the base metadata
 * - Mainnet and testnet node and service endpoints do not use onion hosts
 * - Mainnet and testnet do not share ADM node, IPFS node, or ADM explorer origins
 */
export function findNetworkConfigViolations(
  variant: NetworkConfigVariant,
  config: NetworkConfig,
  references: NetworkConfigReferences
): string[] {
  const schemaViolations = findNetworkConfigSchemaViolations(config)

  if (schemaViolations.length > 0) {
    return schemaViolations
  }

  const violations: string[] = []

  for (const [coin, coinConfig] of Object.entries(config)) {
    for (const field of EXPLORER_FIELDS) {
      const value = coinConfig[field]

      if (value !== undefined && !parseHttpUrl(value)) {
        violations.push(`${coin}.${field}: invalid HTTP(S) URL ${JSON.stringify(value)}`)
      }
    }
  }

  for (const { path: endpointPath, url } of collectNetworkEndpoints(config)) {
    const endpoint = parseHttpUrl(url)

    if (!endpoint) {
      violations.push(`${endpointPath}: invalid HTTP(S) endpoint ${JSON.stringify(url)}`)
    } else if (variant === 'tor' && !isOnionHost(endpoint)) {
      violations.push(`${endpointPath}: Tor endpoints must use onion hosts, found ${url}`)
    } else if (variant !== 'tor' && isOnionHost(endpoint)) {
      violations.push(
        `${endpointPath}: ${variant} endpoints must not use onion hosts, found ${url}`
      )
    }
  }

  if (variant === 'tor') {
    // Only the third-party BTC, DASH, DOGE, and ETH explorers may stay clearnet in Tor
    for (const field of EXPLORER_FIELDS) {
      const value = config.adm?.[field]
      const explorer = parseHttpUrl(value)

      if (explorer && !isOnionHost(explorer)) {
        violations.push(`adm.${field}: Tor ADM explorer links must use onion hosts, found ${value}`)
      }
    }
  }

  if (variant !== 'tor') {
    const otherNetwork = variant === 'mainnet' ? 'testnet' : 'mainnet'
    const forbiddenOrigins = new Set(
      collectAdmNetworkOrigins(references[otherNetwork]).map(({ origin }) => origin)
    )

    for (const { path: fieldPath, origin } of collectAdmNetworkOrigins(config)) {
      if (forbiddenOrigins.has(origin)) {
        violations.push(
          `${fieldPath}: ${variant} configuration uses the ${otherNetwork} origin ${origin}`
        )
      }
    }
  }

  return violations
}

/**
 * Checks that a bundle contains exactly the expected generated network configuration module.
 */
export function findBundledNetworkConfigViolations(
  expectedVariant: NetworkConfigVariant,
  moduleIds: Iterable<string>,
  configsDir: string,
  selectedModuleId = getNetworkConfigVirtualId(expectedVariant)
): string[] {
  const variantsByPath = new Map<string, NetworkConfigVariant>()

  for (const variant of NETWORK_CONFIG_VARIANTS) {
    variantsByPath.set(getNetworkConfigPath(configsDir, variant), variant)
  }

  variantsByPath.set(selectedModuleId, expectedVariant)
  const bundledVariants = new Set<NetworkConfigVariant>()

  for (const moduleId of moduleIds) {
    const variant = variantsByPath.get(normalizePath(moduleId.split('?')[0]))

    if (variant) {
      bundledVariants.add(variant)
    }
  }

  const violations = [...bundledVariants]
    .filter((variant) => variant !== expectedVariant)
    .map((variant) => `the bundle includes the ${variant} network configuration`)

  if (!bundledVariants.has(expectedVariant)) {
    violations.unshift(`the bundle does not include the ${expectedVariant} network configuration`)
  }

  return violations
}

/**
 * Compares the path/value mapping of the final emitted runtime configuration with the generated
 * file. The selected configuration module marks every HTTP(S) URL at load time so `generateBundle`
 * can recover the final URL bound to each config path after every later output transform.
 */
export function findEmittedNetworkConfigViolations(
  variant: NetworkConfigVariant,
  config: NetworkConfig,
  emittedCode: string | null
): string[] {
  if (emittedCode === null) {
    return [`the final emitted chunk did not expose the marked ${variant} network configuration`]
  }

  const generatedUrls = new Map(
    collectConfigUrlEntries(config).map(({ path: fieldPath, url }) => [fieldPath, url])
  )
  const emittedUrls = new Map(
    collectMarkedConfigUrlEntries(emittedCode).map(({ path: fieldPath, url }) => [fieldPath, url])
  )

  if (emittedUrls.size === 0) {
    return [`the final emitted chunk did not expose the marked ${variant} network configuration`]
  }

  const fieldPaths = new Set([...generatedUrls.keys(), ...emittedUrls.keys()])
  const violations: string[] = []

  for (const fieldPath of [...fieldPaths].sort()) {
    const generatedUrl = generatedUrls.get(fieldPath)
    const emittedUrl = emittedUrls.get(fieldPath)

    if (generatedUrl === undefined && emittedUrl !== undefined) {
      violations.push(
        `the emitted ${variant} configuration declares ${fieldPath} = ${emittedUrl}, which the generated file does not declare`
      )
      continue
    }

    if (generatedUrl !== undefined && emittedUrl === undefined) {
      violations.push(
        `the emitted ${variant} configuration does not declare ${fieldPath} = ${generatedUrl}`
      )
      continue
    }

    if (generatedUrl !== emittedUrl) {
      violations.push(
        `the emitted ${variant} configuration sets ${fieldPath} to ${emittedUrl}, expected ${generatedUrl}`
      )
    }
  }

  return violations
}

/**
 * Lists JSON files that are not generated network configurations. Builds never read such files,
 * so a deployment script that replaces or restores one would otherwise ship an unexpected network.
 */
export function findUnexpectedNetworkConfigFiles(fileNames: Iterable<string>): string[] {
  const generatedFileNames = new Set(NETWORK_CONFIG_VARIANTS.map((variant) => `${variant}.json`))

  return [...fileNames]
    .filter((fileName) => fileName.endsWith('.json') && !generatedFileNames.has(fileName))
    .sort()
}

function listDirectory(directory: string): string[] {
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- the configuration directory is derived from the Vite root
    return readdirSync(directory)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []

    throw error
  }
}

/**
 * Resolves `virtual:adamant-network-config` to the generated configuration of the current mode,
 * rejects unsupported modes and unexpected configuration files, and verifies the emitted bundle
 * against the network contract.
 */
export function networkConfigPlugin(target: NetworkBuildTarget): Plugin {
  let variant: NetworkConfigVariant
  let configsDir: string
  let configModuleId: string
  let isBuild = false

  return {
    name: 'adamant-network-config',
    enforce: 'pre',

    configResolved(config) {
      variant = resolveNetworkConfigVariant(target, config.mode)
      configsDir = path.resolve(config.root, 'src', 'config')
      configModuleId = getNetworkConfigVirtualId(variant)
      isBuild = config.command === 'build'

      const unexpectedFiles = findUnexpectedNetworkConfigFiles(listDirectory(configsDir))

      if (unexpectedFiles.length > 0) {
        throw new Error(
          `Unexpected network configuration files in src/config: ${unexpectedFiles.join(', ')}. ` +
            'Builds select a generated configuration by Vite mode and never read these files. ' +
            'Remove them and build Tor with "npm run build:tor" instead of replacing configuration files.'
        )
      }
    },

    resolveId(id) {
      return id === NETWORK_CONFIG_MODULE_ID ? configModuleId : null
    },

    load(id) {
      if (id !== configModuleId) return null

      return renderNetworkConfigModule(readNetworkConfig(configsDir, variant))
    },

    generateBundle(_options, bundle) {
      if (!isBuild) return

      const moduleIds: string[] = []
      const emittedChunks: string[] = []

      for (const output of Object.values(bundle)) {
        if (output.type !== 'chunk') continue

        moduleIds.push(...output.moduleIds)

        if (output.moduleIds.includes(configModuleId)) {
          emittedChunks.push(output.code)
        }
      }

      const config = readNetworkConfig(configsDir, variant)
      const violations = [
        ...findBundledNetworkConfigViolations(variant, moduleIds, configsDir, configModuleId),
        ...findNetworkConfigViolations(variant, config, {
          mainnet: readNetworkConfig(configsDir, 'mainnet'),
          testnet: readNetworkConfig(configsDir, 'testnet')
        }),
        ...findEmittedNetworkConfigViolations(
          variant,
          config,
          emittedChunks.length > 0 ? emittedChunks.join('\n') : null
        )
      ]

      if (violations.length > 0) {
        this.error(
          `Network configuration build gate rejected the ${variant} bundle:\n${violations.join('\n')}`
        )
      }

      for (const output of Object.values(bundle)) {
        if (output.type !== 'chunk' || !output.moduleIds.includes(configModuleId)) continue

        output.code = stripMarkedConfigUrlExpressions(output.code)
      }
    }
  }
}

function getNetworkConfigPath(configsDir: string, variant: NetworkConfigVariant): string {
  return normalizePath(path.join(configsDir, `${variant}.json`))
}

function getNetworkConfigVirtualId(variant: NetworkConfigVariant): string {
  return `\0adamant-network-config:${variant}`
}

function readNetworkConfig(configsDir: string, variant: NetworkConfigVariant): NetworkConfig {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- variant names come from a fixed allowlist
  return JSON.parse(readFileSync(getNetworkConfigPath(configsDir, variant), 'utf8'))
}

function renderNetworkConfigModule(config: NetworkConfig): string {
  return [`const config = ${renderNetworkConfigValue(config)}`, 'export default config'].join('\n')
}

function renderNetworkConfigValue(value: unknown, currentPath = ''): string {
  if (typeof value === 'string') {
    if (currentPath && parseHttpUrl(value)) {
      return `(globalThis.${NETWORK_CONFIG_URL_REGISTRY} ??= {}, globalThis.${NETWORK_CONFIG_URL_REGISTRY}[${JSON.stringify(`${NETWORK_CONFIG_URL_MARKER}${currentPath}`)}] = ${JSON.stringify(value)})`
    }

    return JSON.stringify(value)
  }

  if (Array.isArray(value)) {
    return `[${value
      .map((entry, index) => renderNetworkConfigValue(entry, `${currentPath}[${index}]`))
      .join(', ')}]`
  }

  if (isPlainObject(value)) {
    return `{${Object.entries(value)
      .map(([key, entryValue]) => {
        const nextPath = currentPath ? `${currentPath}.${key}` : key

        return `${JSON.stringify(key)}: ${renderNetworkConfigValue(entryValue, nextPath)}`
      })
      .join(', ')}}`
  }

  return JSON.stringify(value)
}

function findEndpointListViolations(listPath: string, endpointList: unknown): string[] {
  if (endpointList === undefined) {
    return [`${listPath}: missing endpoint list`]
  }

  if (!isPlainObject(endpointList)) {
    return [`${listPath}: expected an object`]
  }

  const list = endpointList.list

  if (!Array.isArray(list) || list.length === 0) {
    return [`${listPath}.list: expected a non-empty array of endpoints`]
  }

  return list.flatMap((entry, index) => {
    if (!isPlainObject(entry)) {
      return [`${listPath}.list[${index}]: expected an endpoint object`]
    }

    const issues: string[] = []

    if (typeof entry.url !== 'string') {
      issues.push(`${listPath}.list[${index}].url: expected a string`)
    }

    if (entry.alt_ip !== undefined && typeof entry.alt_ip !== 'string') {
      issues.push(`${listPath}.list[${index}].alt_ip: expected a string`)
    }

    return issues
  })
}

function collectListEndpoints(listPath: string, endpointList: EndpointList | undefined) {
  return (endpointList?.list ?? []).flatMap((entry, index) => [
    { path: `${listPath}.list[${index}].url`, url: entry.url },
    ...(entry.alt_ip === undefined
      ? []
      : [{ path: `${listPath}.list[${index}].alt_ip`, url: entry.alt_ip }])
  ])
}

function collectAdmNetworkOrigins(config: NetworkConfig): { path: string; origin: string }[] {
  const adm = config.adm ?? {}
  const fields = [
    ...collectListEndpoints('adm.nodes', adm.nodes),
    ...collectListEndpoints('adm.services.ipfsNode', adm.services?.ipfsNode),
    ...EXPLORER_FIELDS.map((field) => ({ path: `adm.${field}`, url: adm[field] }))
  ]

  return fields.flatMap(({ path: fieldPath, url }) => {
    const parsedUrl = parseHttpUrl(url)

    return parsedUrl ? [{ path: fieldPath, origin: parsedUrl.origin }] : []
  })
}

function collectConfigUrlEntries(
  value: unknown,
  currentPath = ''
): { path: string; url: string }[] {
  if (typeof value === 'string') {
    return currentPath && parseHttpUrl(value) ? [{ path: currentPath, url: value }] : []
  }

  if (Array.isArray(value)) {
    return value.flatMap((entry, index) =>
      collectConfigUrlEntries(entry, `${currentPath}[${index}]`)
    )
  }

  if (isPlainObject(value)) {
    return Object.entries(value).flatMap(([key, entryValue]) =>
      collectConfigUrlEntries(entryValue, currentPath ? `${currentPath}.${key}` : key)
    )
  }

  return []
}

function collectMarkedConfigUrlEntries(code: string): { path: string; url: string }[] {
  return [...code.matchAll(MARKED_NETWORK_CONFIG_URL_PATTERN)].map((match) => ({
    path: match[1],
    url: match[2]
  }))
}

function stripMarkedConfigUrlExpressions(code: string): string {
  return code.replace(MARKED_NETWORK_CONFIG_URL_EXPRESSION_PATTERN, '$2')
}

function getServices(coinConfig: unknown): Record<string, unknown> {
  if (!isPlainObject(coinConfig) || !isPlainObject(coinConfig.services)) return {}

  return coinConfig.services
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function parseHttpUrl(value: unknown): URL | null {
  if (typeof value !== 'string') return null

  try {
    const url = new URL(value)

    return url.protocol === 'http:' || url.protocol === 'https:' ? url : null
  } catch {
    return null
  }
}

function isOnionHost(url: URL): boolean {
  return url.hostname.endsWith('.onion')
}
