export const COMMON_ICON_SIZE = 24
export const COMMON_COMPACT_ICON_SIZE = 20
export const COMMON_ICON_BUTTON_SIZE = 36
export const COMMON_INLINE_SPINNER_SIZE = 24
export const COMMON_TRIGGER_ICON_SIZE = 28
export const COMMON_REACTION_MORE_BUTTON_SIZE = 32
