export const AUTH_FORM_TOGGLE_BUTTON_SIZE = 28
export const AUTH_FORM_TOGGLE_ICON_SIZE = 24
export const AUTH_FORM_MENU_ICON_SIZE = 24
export const AUTH_FORM_COPY_ICON_SIZE = 20
export const AUTH_FORM_SUBMIT_SPINNER_SIZE = 24
export const AUTH_FORM_SETTINGS_BUTTON_SIZE = 32
