export const CHAT_STATUS_ICON_SIZE = 13
export const CHAT_STATUS_ICON_ERROR_SIZE = 15

export const CHAT_ACTIONS_DROPDOWN_MIN_WIDTH = 80
export const CHAT_ACTIONS_DROPDOWN_MAX_WIDTH = 264
export const CHAT_ACTIONS_DROPDOWN_BUTTON_SIZE = 28
export const CHAT_ACTIONS_DROPDOWN_ICON_SIZE = 24

export const CHAT_ATTACHMENT_PREVIEW_SIZE = 64
export const CHAT_MODAL_FILE_MAX_WIDTH = 500
export const CHAT_MODAL_FILE_MAX_HEIGHT = 250
export const CHAT_MODAL_FILE_ICON_SIZE = 128
export const CHAT_FILES_PREVIEW_SIZE = 80
export const CHAT_FILES_PREVIEW_REMOVE_ICON_SIZE = 18
export const CHAT_FORM_SEND_ICON_SIZE = 22
export const CHAT_REACTION_AVATAR_SIZE = 16
export const QUOTED_MESSAGE_LOADING_SPINNER_SIZE = 16
