export const CHAT_STATUS_ICON_SIZE = 13
export const CHAT_STATUS_ICON_ERROR_SIZE = 15

export const CHAT_ACTIONS_DROPDOWN_MIN_WIDTH = 80
export const CHAT_ACTIONS_DROPDOWN_MAX_WIDTH = 264
export const CHAT_ACTIONS_DROPDOWN_BUTTON_SIZE = 28
export const CHAT_ACTIONS_DROPDOWN_ICON_SIZE = 24
