export const CHAT_TOOLBAR_UNREAD_COUNTER_MAX = 99

export const CHAT_CONNECTION_SPINNER_SIZE = 32
export const CHATS_CONNECTION_SPINNER_SIZE = CHAT_CONNECTION_SPINNER_SIZE
export const CHATS_SCROLL_OFFSET = 64
