import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

import { ALLOWED_URI_PROTOCOLS, ALLOWED_URI_SCHEMES } from '@/lib/uriSchemes'

/**
 * The URI scheme allowlist must have exactly one definition.
 *
 * It previously existed as three hardcoded copies — the markdown renderer, `SafeHtml` and
 * `openExternalLink` — plus a fourth in the Electron main process, and they drifted: the desktop
 * copy silently blocked the `ethereum:`, `dash:` and `doge:` links the app itself generates.
 * Reading the sources here is the same approach the UI contract specs already use.
 */
const SOURCES = [
  'src/lib/markdown.ts',
  'src/components/common/SafeHtml.ts',
  'src/lib/openExternalLink.ts',
  'src/electron/main.js'
]

describe('URI scheme allowlist has a single source', () => {
  it.each(SOURCES)('%s imports the shared list instead of defining its own', (path) => {
    const source = readFileSync(path, 'utf8')

    expect(source).toContain("from '@/lib/uriSchemes'")
  })

  it.each(SOURCES)('%s does not hardcode a scheme collection', (path) => {
    const source = readFileSync(path, 'utf8')

    // A literal set or array of schemes is what drifted last time
    expect(source).not.toMatch(/EXTERNAL_URL_SCHEMES|ALLOWED_SCHEMES\s*=/)
    expect(source).not.toMatch(/new Set\(\[\s*'https?:'/)
  })

  it('covers the schemes the desktop build has to open', () => {
    // These are generated by `generateURI`; the Electron handler must accept them
    for (const scheme of ['adm', 'bitcoin', 'ethereum', 'dash', 'doge', 'https']) {
      expect(ALLOWED_URI_SCHEMES, scheme).toContain(scheme)
      expect(ALLOWED_URI_PROTOCOLS.has(`${scheme}:`), scheme).toBe(true)
    }
  })
})
