name: Build Electron [Mac]

on:
  push:
    branches:
      - master
      - dev

env:
  GH_TOKEN: ${{ secrets.github_token }}
  CSC_LINK: ${{ secrets.CSC_LINK }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v3

      - name: Setup Node version 🍀
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies ⚙️
        run: npm ci

      - name: Build and Signing Electron App 🛠️
        run: |
          npm run electron:build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-release-app
          path: |
            release-electron/*.dmg
            release-electron/*.blockmap
            release-electron/*.yaml
            release-electron/*.yml
