name: Build Electron [Mac]

on:
  push:
    branches:
      - master
      - dev

env:
  GH_TOKEN: ${{ secrets.github_token }}
  CSC_LINK: ${{ secrets.CSC_LINK }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  APPLE_NOTARIZE: true # notarize the app after build

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Setup Node version 🍀
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies ⚙️
        run: npm ci

      - name: Build and Sign Electron App 🛠️
        run: |
          npm run schema:generate
          npm run electron:build

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-app
          path: |
            release-electron/*.dmg
