name: GitHub Pages
on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node version 🍀
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Configure GitHub Pages ⚙️
        uses: actions/configure-pages@v5

      - name: Install dependencies 📦
        run: npm ci

      - name: Build PWA 🛠️
        run: |
          npm run schema:generate
          npm run build
        env:
          VITE_PUBLIC_PATH: "/${{ github.event.repository.name }}/"
          VITE_ROUTER_HISTORY_MODE: hash

      - name: Upload artifacts 📁
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
