name: Preview Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

env:
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  PREVIEW_DOMAIN: https://msg-adamant-pr-${{ github.event.number }}.surge.sh

jobs:
  build-and-deploy-to-surge:
    name: Build and Deploy to surge
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Setup Node version 🍀
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies ⚙️
        run: npm ci

      - name: Build PWA 🛠️
        run: |
          npm run schema:generate
          npm run build

      - name: Archive artifacts 📁
        uses: actions/upload-artifact@v4
        with:
          path: dist

      - name: Deploy to surge 🚀
        run: |
          npm install --global surge
          surge ./dist ${{ env.PREVIEW_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment PR 💬
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Deployed to ${{ env.PREVIEW_DOMAIN }} 🚀
          comment_tag: deploy-message
