name: Preview Teardown Workflow

on:
  pull_request:
    types:
      - closed

env:
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  PREVIEW_DOMAIN: https://msg-adamant-pr-${{ github.event.number }}.surge.sh

jobs:
  tear-down-preview-domain:
    name: Tear down preview domain job
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      pull-requests: write
    steps:
      - name: Tear down ${{ env.PREVIEW_DOMAIN }} preview domain 🥲
        run: |
          npm install --global surge
          surge teardown ${{ env.PREVIEW_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment PR 💬
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Successfully tore down ${{ env.PREVIEW_DOMAIN }} 🥲
          comment_tag: teardown-message
